### ISSUE TITLE
Remove samples from install

### ISSUE THREAD

**Issue by omerbensaadon** [csantanapr/knative-kind#16]
Would be great if this repo allowed you to `curl` all of the scripts and simply install Knative on Kind without any of the samples!

**Comment by csantanapr** [comment]
Yes I agree this is good idea. 
Let's leave `get.konk.dev` for the folks using it today and assume it comes with all batteries included and come up with a new domain name `install.konk.dev` ?

**Comment by csantanapr** [comment]
DNS is updated should be available in a few `curl -sL install.konk.dev | bash`

**Comment by omerbensaadon** [comment]
I think we can close?
