### ISSUE TITLE
KonK fails install on Ubuntu 

### ISSUE THREAD

**Issue by omerbensaadon** [csantanapr/knative-kind#29]
ubuntu@konk:$ curl -sL install.konk.dev | bash
 ✅ Checking dependencies...
KinD version is kind v0.10.0 go1.15.7 linux/amd64
ERROR: failed to create cluster: failed to list clusters: command "docker ps -a --filter label=io.x-k8s.kind.cluster=knative --format '{{.Names}}'" failed with error: exit status 1
Command Output: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.x-k8s.kind.cluster%3Dknative%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied

ubuntu@konk:$ sudo curl -sL install.konk.dev | bash
 ✅ Checking dependencies...
KinD version is kind v0.10.0 go1.15.7 linux/amd64
ERROR: failed to create cluster: failed to list clusters: command "docker ps -a --filter label=io.x-k8s.kind.cluster=knative --format '{{.Names}}'" failed with error: exit status 1
Command Output: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.x-k8s.kind.cluster%3Dknative%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
ubuntu@konk:~$

From User: 
> so familiar fix with script - check which os within your script and then execute the right command
> any command on Ubuntu that needs to interact with system requires a sudo in front :slightly_smiling_face:

**Comment by schattmicro** [comment]
Planning to raise a PR to fix the issue based on my conversation with Omer(PM), please stay tuned for a PR coming your way.

**Comment by csantanapr** [comment]
I will double check, but from what I'm aware there is no need to use `sudo`

If you can run `docker` without `sudo` or not being `root`  then you don't need `sudo` to create a kind cluster.

To avoid `sudo docker ...` you need to add the user to the `docker` group on Linux this will allow users of the group to run `docker ..` without `sudo`

**Comment by csantanapr** [comment]
detecting Linux and forcing the user to use `sudo` would be surprise and a security surprise and the user would not like to use it.

**Comment by csantanapr** [comment]
We can doc something like if you `can't run docker without sudo` you can re-run the command with `sudo`

**Comment by schattmicro** [comment]
Alright, I understand the security aspect , but please advise how an Ubuntu user can run the script at its current state to install and configure kind , the purpose is to automate the installation , the user who is automating installation is aware of the security risks , if not he should not proceed , we can definitely give the use heads up , ask for confirmation and then prompt the user to enter masked password

**Comment by schattmicro** [comment]
> We can doc something like if you `can't run docker without sudo` you can re-run the command with `sudo`

the user needs to make in-line changes to the script to insert what you are suggesting which is not a good experience from end user standpoint

**Comment by csantanapr** [comment]
maybe we can put something in the script to detect if user can't use `docker` without `sudo` and then add the `sudo` in front automatically.

**Comment by csantanapr** [comment]
Have the script be smart and check, if you are on Linux and not need `sudo` then we don't use `sudo` and if the user can't run `docker run` without `sudo` we print the warning message and then we add the sudo automatically they will be prompted for password for continue

**Comment by schattmicro** [comment]
you dont need that , you can find the os type , if ubuntu is detected , call a function to ask permission from user and make him aware what he is doing and then do sudo -s , bit aggressive and risky I agree but we putting the onus on user

**Comment by schattmicro** [comment]
with sudo -s you dont have to prefix sudo before each command

**Comment by csantanapr** [comment]
>you dont need that , you can find the os type , if ubuntu is detected , call a function to ask permission from user and make him aware what he is doing and then do sudo -s , bit aggressive and risky I agree but we putting the onus on user

yeah lets do this and see what feedback we get. looking forward to PR

**Comment by schattmicro** [comment]
Thanks so much for reviewing and vetting the idea, hope it augurs well for us and the community.

**Comment by schattmicro** [comment]
Hey @csantanapr , devised a solution which would require to touch any of your existing scripts to install Konk on Ubuntu. 

1. Run a top level script inline to determine os type 
2. if ubuntu - then execute curl -sL install.konk.dev | sudo -s bash - I will test with in-line pipes with exported variables to pass os type
Step 2 will prompt the non root user to enter sudo password for the non root user configured in /etc/sudoers file when the user account had been created and added to sudoers group. If the logged in user is a privileged user , the no prompt and the script will execute as is without any fiddling

Let me know your thoughts.

**Comment by schattmicro** [comment]
1. Added a new script locally(not checked in) to determine os type or linux distro called 00-os-type.sh which returns os_type as either "OSX",  or "UBUNTU", "CENTOS" and other possible Linux Distros with the return string in all UPPERCASE
2. Modified the install.sh to factor in conditional sudo -s for UBUNTU only, can be improved a lot
Here is how it looks like 
#!/usr/bin/env bash

set -eo pipefail

echo -e "\033[0;92m ✅ Checking os... \033[0m"
os_type=$(curl -sL https://raw.githubusercontent.com/csantanapr/knative-kind/master/00-os-type.sh | bash)
echo -e "\033[0;92m ✅ Checking dependencies... \033[0m"
STARTTIME=$(date +%s)
if [ $os_type -eq "UBUNTU" ]; then
        curl -sL https://raw.githubusercontent.com/csantanapr/knative-kind/master/01-kind.sh | sudo -s bash
fi
curl -sL https://raw.githubusercontent.com/csantanapr/knative-kind/master/01-kind.sh | bash
echo -e "🍿 Installing Knative Serving... \033[0m"
curl -sL https://raw.githubusercontent.com/csantanapr/knative-kind/master/02-serving.sh | bash
echo -e "🔥 Installing Knative Eventing... \033[0m"
curl -sL https://raw.githubusercontent.com/csantanapr/knative-kind/master/04-eventing.sh | bash
DURATION=$(($(date +%s) - $STARTTIME))
echo -e "\033[0;92m 🚀 Knative install took: $(($DURATION / 60))m$(($DURATION % 60))s \033[0m"
echo -e "\033[0;92m 🎉 Now have some fun with Serverless and Event Driven Apps \033[0m"

**Comment by schattmicro** [comment]
In case you are happy with the changes, I can raise a PR, just wanted to make sure code base changes are bare minimum and new functionality is reusable without introducing breaking changes

**Comment by omerbensaadon** [comment]
@schattmicro I would raise a PR regardless and carry this discussion over there :)

**Comment by schattmicro** [comment]
Yes @omerbensaadon , Carlos and I had productive discussion this PM and we figured out a better option to resolve the issue by updating the readme. I am grateful to Carlos for giving me a better insight , I will raise a PR tonight to update the readme file.

**Comment by csantanapr** [comment]
This is addressed now
