### ISSUE TITLE
Issue with Kourier

### ISSUE THREAD

**Issue by salaboy** [csantanapr/knative-kind#46]
Lately, I've been getting this issue, 
I think this started happening after the Domain Mapping introduction

```
🔌 Installing Knative Serving Networking Layer kourier... 
Error from server (InternalError): error when creating "https://github.com/knative-sandbox/net-kourier/releases/download/v0.23.0/kourier.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": dial tcp 10.96.67.141:443: connect: connection refused
```

**Comment by fc7** [comment]
I had the same issue 2 hours ago. When I tried again it worked fine.

**Comment by csantanapr** [comment]
Interesting starting to see this today.
It happens more often on 0.24 than 0.23
I opened an issue in serving https://github.com/knative/serving/issues/11712
@salaboy @fc7 please comment on the issue that you can seeing the problem, I was afraid it was my local network only.

**Comment by csantanapr** [comment]
@salaboy 
>I think this started happening after the Domain Mapping introduction

Is not related to domain mapping, the problem happens in kourier yaml which is way before applying the domain mapping yaml.
Is related to the knative serving config webhook

**Comment by csantanapr** [comment]
I have not seen the problem with the extra retry, please open a new issue if this happens again
